ECONOMY_PRICE_DRIFT_MIN = -5
ECONOMY_PRICE_DRIFT_MAX = 5

ECONOMY_STOCK_PRESSURE_25_MIN = 8
ECONOMY_STOCK_PRESSURE_25_MAX = 20

ECONOMY_STOCK_PRESSURE_150_MIN = -8
ECONOMY_STOCK_PRESSURE_150_MAX = -2

ECONOMY_NEW_PRICE_MULTIPLIER = 0.15

ECONOMY_MIN_PRICE_MULTIPLIER = 0.35

ECONOMY_RESOURCE_CHANGE_MIN = -3
ECONOMY_RESOURCE_CHANGE_MAX = 8
