NATIVE_RESOURCES_BASE_PRICE_MULTIPLIER = 0.7
NATIVE_RESOURCES_STOCK_MIN_QUANTITY = 80
NATIVE_RESOURCES_STOCK_MAX_QUANTITY = 200

IMPORTED_RESOURCES_BASE_PRICE_MULTIPLIER = 1.5
IMPORTED_RESOURCES_STOCK_MIN_QUANTITY = 10
IMPORTED_RESOURCES_STOCK_MAX_QUANTITY = 40

STANDARD_RESOURCES_MIN_BASE_PRICE_MULTIPLIER = 0.7
STANDARD_RESOURCES_MAX_BASE_PRICE_MULTIPLIER = 1.3
