PLANET_CONSTRUCTION_MODIFIER_MIN = 5
PLANET_CONSTRUCTION_MODIFIER_MAX = 20
PLANET_CONSTRUCTION_MODIFIER_STEP = 5

PLANET_POPULATION_MIN = 300
PLANET_POPULATION_MAX = 1000

PLANET_MAX_POPULATION_MIN = 3000
PLANET_MAX_POPULATION_MAX = 11000
PLANET_MAX_POPULATION_STEP = 1000

PLANET_HEALTH_MIN = 40
PLANET_HEALTH_MAX = 80

PLANET_HAPPINESS_MIN = 40
PLANET_HAPPINESS_MAX = 80

PLANET_SAFETY_MIN = 50
PLANET_SAFETY_MAX = 70
